name: Typo Check Action

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - name: Checkout Actions Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Check spelling
      uses: crate-ci/typos@b74202f74b4346efdbce7801d187ec57b266bac8 # master
